// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $contact from "./routes/contact.tsx";
import * as $index from "./routes/index.tsx";
import * as $posts_slug_index from "./routes/posts/[slug]/index.tsx";
import * as $posts_slug_transcript from "./routes/posts/[slug]/transcript.tsx";
import * as $posts_index from "./routes/posts/index.tsx";
import * as $subscription_confirmation from "./routes/subscription-confirmation.tsx";
import * as $where_to_find from "./routes/where-to-find.tsx";
import * as $AnnouncementBanner from "./islands/AnnouncementBanner.tsx";
import * as $FoldingSection from "./islands/FoldingSection.tsx";
import * as $Header from "./islands/Header.tsx";
import * as $SubscribeCta from "./islands/SubscribeCta.tsx";
import * as $SubscribePopup from "./islands/SubscribePopup.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/contact.tsx": $contact,
    "./routes/index.tsx": $index,
    "./routes/posts/[slug]/index.tsx": $posts_slug_index,
    "./routes/posts/[slug]/transcript.tsx": $posts_slug_transcript,
    "./routes/posts/index.tsx": $posts_index,
    "./routes/subscription-confirmation.tsx": $subscription_confirmation,
    "./routes/where-to-find.tsx": $where_to_find,
  },
  islands: {
    "./islands/AnnouncementBanner.tsx": $AnnouncementBanner,
    "./islands/FoldingSection.tsx": $FoldingSection,
    "./islands/Header.tsx": $Header,
    "./islands/SubscribeCta.tsx": $SubscribeCta,
    "./islands/SubscribePopup.tsx": $SubscribePopup,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
