name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: 1.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Install Puppeteer
        run: deno task install-puppeteer

      - name: Start Fresh server and wait for it to be ready
        run: |
          deno task start &
          deno task wait-for-server

      - name: Run integration tests
        run: |
          # Run the test twice to reduce flakes
          # Sometimes tests may fail due to resource leaks that are hard to figure out
          # Running twice increases the chances of a successful test run
          deno task test:integration || deno task test:integration