name: CI

on: [push]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: 2.x

      - name: Check formatting
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Start Fresh server and wait for it to be ready
        run: |
          deno task start &
          deno task wait-for-server

      - name: Run integration tests
        run: deno task test:integration
